### ISSUE TITLE
Looking for a new project maintainer

### ISSUE THREAD

**Issue by edavis** [edavis/org-opml#12]
If you’re interested in taking over this project, please get in touch via issue #12 or via the email address in my profile.

I started this project as a way to teach myself the internals of org mode but I haven’t used it in years. I don’t even do much with OPML or org mode anymore.

It really could use some polish and cleanups, especially getting it added to the package repositories available for Emacs and converting the Python script into native elisp. But it’ll be your package if you adopt it to do whatever you want with it.

**Comment by tonglianheng** [comment]
Hi edavis,

I am a really big fan of org and has been using it for quite a few years. I am also a power user of emacs and has written a few modes and lisp functions for emacs.  I also teach python, so this project would also serve as a good example for me too.  I am therefore interested in working on the project and if you are interested please give me an email and we can discuss more.

Best regards,

Lianheng

**Comment by bsima** [comment]
@edavis :hand: I'm also interested! I too have lots of experience with elisp and python.

Perhaps an "org-opml" [Github Organization](https://github.com/organizations/new) can be created to host this repo, and both @tonglianheng and I could be the first admins?

First order of business would be to get this package on melpa :)

**Comment by tonglianheng** [comment]
@edavis @bsima, I agree, this package should be in melpa.  And I think the more maintainers the better.

**Comment by edavis** [comment]
@bsima @tonglianheng Hello!

As for next steps on ownership, whatever you two decide on is fine by me. I have no preference re: Github Org vs. regular project. Feel free to use this thread to figure that part out. Let me know if you need anything from me.

Once org-opml has been forked and given a new home, I'll update my README to point to the new spot. At that that point, it'll be yours to do whatever you want with it.

**Comment by tonglianheng** [comment]
@bsima @edavis, I believe with @bsima that a Github Org may be a good idea.  Shall we just call it org-opml?

**Comment by bsima** [comment]
I created a Github Org here: https://github.com/org-opml and I added @tonglianheng.

I didn't add @edavis because I figured you wanted to be hands off at this point but if you want in just let me know

Next week I will be at a conference and mostly afk, but @tonglianheng you should have push access to do whatever dev stuff you want.

**Comment by tonglianheng** [comment]
@bsima, thanks!

**Comment by edavis** [comment]
@bsima @tonglianheng Looks great! So glad this project found a new home. Can't wait to see what you two have in store for it.

**Comment by edavis** [comment]
@bsima Didn't think of this until just now: Would it be "cleaner" for me to transfer ownership of this repo to you guys instead of it being a fork?

Otherwise, won't the "This branch is N commits ahead of edavis:master" message always be displayed?

Your call either way. Just wanted to toss it out there.

**Comment by tonglianheng** [comment]
Hi Eric,

Either way will be fine for me at least.  Also, I would suggest that as people are used to edavis/org-opml may be a mention of its migrating to org-opml in the original branch would be a good idea?

Best regards,

Lianheng
