### ISSUE TITLE
code is not compatible with emacs 25

### ISSUE THREAD

**Issue by Unixware** [edavis/org-opml#16]
Does not seem to work correctly, export produces OPML file but when I import it on an OPML app (projekt on Symbian) entries are there, but completely empty. I even tried emacs 24 same results, are you using a special emacs build?

**Comment by edavis** [comment]
Hi @Unixware — You'll have better luck opening this ticket at the project's new home: https://github.com/org-opml/org-opml

I haven't worked on any of this code in years. Here's the thread where the new maintainers took over: https://github.com/edavis/org-opml/issues/12

(Though, FWIW, no special build for Emacs should be required.)

Good luck!
