### ISSUE TITLE
Needs for this mode...

### ISSUE THREAD

**Issue by DSMasterson** [edavis/org-opml#2]
Thanks for creating the OPML mode for Org.  This is the one thing that I have had a problem with.  Most outliners on iOS support OPML whereas most outliners on PCs (including Org) didn't.  For a standard to promote the interchange of outlines, it wasn't very standard...

There are a few things that this could use:
1. Better documentation, obviously, on the limits of the OPML conversion.
2. Get this into the contrib section of Org so that it's more generally available.
3. More flexibility to handle OPML 1.0 and 2.0 as well as 0.0 (ie. an OPML that doesn't have a proper header to identify its type).
4. A key to write a new Org file from the OPML file so that you can permanently convert.
5. Better errors if the OPML (or Org) file doesn't conform to expected.
6. Automated fixups for files that are mostly correct.

**Comment by bsima** [comment]
see: https://github.com/org-opml/org-opml/issues/2
