### ISSUE TITLE
Feature Request: Allow installation through MELPA or similar

### ISSUE THREAD

**Issue by kepi** [edavis/org-opml#8]
It will be great to have easier way to install your package through package-install command.

**Comment by org-dive** [comment]
I started using aquamacs a few months ago and tried installing org/opml recently.  However, I am still not able to open opml in aqua.  Any advice?

**Comment by Conaws** [comment]
+1 to this, also, more documentation on how to make sure python script is in the right place

**Comment by bsima** [comment]
see also: https://github.com/edavis/org-opml/issues/8
